version = 1

exclude_patterns = [
    "lib/**",
    "css/**",
    "public/**",
    "img/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  runtime_env = [
    "node",
    "browser"
  ]